### ISSUE TITLE
Message Resolver

### ISSUE THREAD

**Issue by marcemira** [vladaspasic/ember-cli-data-validation#3]
Hello, this a very cool addon! Although, I still fail to understand how to customize messages.. You gave some examples but I can figure out how to implement it. Can you please explain a little more? I'll appreciate it :). Give an example of how to translate i.e. require. Thanks!

**Comment by vladaspasic** [comment]
Hi @marcemira,

I am sorry I could not answer you earlier. When a Validation of the attribute fails, `Validator` creates a error message by invoking the `MessageResolver.resolve` method. This method will create couple of message keys. These keys are used to locate the error message.

For instance if we have a `Model` with 2 attributes, declared like this:

``` javascript
   DS.Model.extend({
        name: DS.attr('string', {
            validation: {
                required: true
            }
        }),
       age: DS.attr('number', {
            validation: {
                required: true,
                min: 18
            }
        })
    })
```

And we have an Object of error messages that we have set in the custom implementation of the `MessageResolver`:

``` javascript
import MessageResolver from 'ember-cli-data-validation/message-resolver';

export default MessageResolver.extend({
    catalog: Ember.computed(function() {
        return {
            'required': 'Field %@ is required',
            'min.string': 'String must have more than %@ characters',
            'min.number': 'Number must be larger than %@',
        };
    }),
    resolveMessage: function(key) {
        var catalog = this.get('catalog');

        return Ember.get(catalog, key);
    }
});
```

For the `name` attribute and the `required` validator, `MessageResolver.parseName` will generate these keys:

``` javascript
{
  attributeType: 'string',
  validatorType: 'required',
  fullName: 'required.string',
}
```

For the `name` attribute and the `min` validator, `MessageResolver.parseName` will generate these keys:

``` javascript
{
  attributeType: 'string',
  validatorType: 'min',
  fullName: 'min.string',
}
```

For the `age` attribute and the `required` validator, `MessageResolver.parseName` will generate these keys:

``` javascript
{
  attributeType: 'number',
  validatorType: 'required',
  fullName: 'required.number',
}
```

For the `age` attribute and the `min` validator, `MessageResolver.parseName` will generate these keys:

``` javascript
{
  attributeType: 'number',
  validatorType: 'min',
  fullName: 'min.number',
}
```

Once the keys are generated, the `MessageResolver.resolve` method would first invoke the `resolveMessage` method with the `fullName` value, if the message does not exists, then it would be invoked again with the `validatorType` value.

So when the validation fails for the `name` attribute with `required` Validator, the `resolveMessage` would be invoked with the `fullName` value, which is `required.string`. This key does not exists in our `catalog`, so the resolver will try again with the `validatorType` value, which is `required`. This key exists, and the `Field %@ is required` would be returned.

For the `min` Validator and the `name` attribute, the `String must have more than %@ characters` would be returned, as the `fullName` value is `min.string` which is present in the `catalog`.

For the `age` attribute the `required` Validator would have the same message as the `name`, as there is no `required.number` key present in the catalog. But for the `min` Validator, the message would be `Number must be larger than %@`.

Once the message is found, it is stored in the cache for the current looked up key.

I hope this is a bit clearer now for you.

While writing this I saw it could be useful to have the attribute name in the searched keys and perhaps the model name.

**Comment by marcemira** [comment]
@vladaspasic Thanks you so much! this is great and very useful :grin:

**Comment by vladaspasic** [comment]
HI @marcemira I have made some small changes to the `MessageResolver`. Now the `MessageResolver.parseName` would return this:

``` javascript
{
  attributeType: 'number',
  validatorType: 'min',
  modelType: 'myModel',
  validatorPath: 'min.number',
  modelPath: 'myModel.age.min'
}
```

Now there is a new path that has a `DS.Model` name generated by the `DS.Store`. Now you can customise  the error message for each Model attribute and a validator type.

**Comment by marcemira** [comment]
@vladaspasic awesome :grinning: :tada:
