### ISSUE TITLE
Rejected save promise object is useless 

### ISSUE THREAD

**Issue by marcemira** [vladaspasic/ember-cli-data-validation#4]
Hey, hello again.. I was trying to use the reject on my save method but it always returns a `new DS.InvalidError()` that doesn't contain any useful data. Here: `https://github.com/vladaspasic/ember-cli-data-validation/blob/master/addon/mixins/validator.js#L141` Is is possible to have it return the usual error object with the payload instead? Thanks

**Comment by vladaspasic** [comment]
Hi @marcemira,

You are right, it makes no sense. I will create a custom error that would contain a Error message and the `DS.Errors` object. The message would be extracted from the `MessageResolver`. I will let you know when the release is ready, so you can update the dependency.

**Comment by marcemira** [comment]
Hey @vladaspasic thank you very much! :grin::+1:

**Comment by vladaspasic** [comment]
Hi @marcemira I have published the addon with the changes, version is `0.1.0`. Now the Promise is rejected with the `ValidationError` that contains the `DS.Errors` object.

**Comment by marcemira** [comment]
@vladaspasic Thank you :+1:
